### PR TITLE
fixed bug #818

### LINKED ISSUE #818: class2tree error (doubt, potential bug)
<details> <summary><strong>Session Info</strong></summary>

```r
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Linux Mint 19               
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language es_ES                       
 collate  es_ES.UTF-8                 
 ctype    es_ES.UTF-8                 
 tz       Europe/Madrid               
 date     2020-04-28                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 ape           5.3     2019-03-17 [1] CRAN (R 3.6.1)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.6   2020-04-05 [1] CRAN (R 3.6.3)
 BiocManager   1.30.10 2019-11-16 [1] CRAN (R 3.6.1)
 bold          0.9.0   2019-06-27 [1] CRAN (R 3.6.2)
 broom         0.5.6   2020-04-20 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.3)
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.0)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
 codetools     0.2-16  2018-12-24 [4] CRAN (R 3.5.2)
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 crul          0.9.0   2019-11-06 [1] CRAN (R 3.6.1)
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.1)
 data.table    1.12.8  2019-12-09 [1] CRAN (R 3.6.1)
 DBI           1.1.0   2019-12-15 [1] CRAN (R 3.6.1)
 dbplyr        1.4.3   2020-04-19 [1] CRAN (R 3.6.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
 devtools      2.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
 dplyr       * 0.8.5   2020-03-07 [1] CRAN (R 3.6.3)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
 forcats     * 0.5.0   2020-03-01 [1] CRAN (R 3.6.3)
 foreach       1.5.0   2020-03-30 [1] CRAN (R 3.6.3)
 fs            1.4.1   2020-04-04 [1] CRAN (R 3.6.3)
 generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.0)
 ggplot2     * 3.3.0   2020-03-05 [1] CRAN (R 3.6.3)
 ggrepel     * 0.8.2   2020-03-08 [1] CRAN (R 3.6.3)
 ggstance      0.3.4   2020-04-02 [1] CRAN (R 3.6.3)
 ggtree      * 2.0.2   2020-03-16 [1] Bioconductor  
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.0)
 haven         2.2.0   2019-11-08 [1] CRAN (R 3.6.1)
 hms           0.5.3   2020-01-08 [1] CRAN (R 3.6.2)
 httpcode      0.3.0   2020-04-10 [1] CRAN (R 3.6.3)
 httr          1.4.1   2019-08-05 [1] CRAN (R 3.6.1)
 iterators     1.0.12  2019-07-26 [1] CRAN (R 3.6.1)
 jsonlite      1.6.1   2020-02-02 [1] CRAN (R 3.6.2)
 lattice       0.20-41 2020-04-02 [4] CRAN (R 3.6.3)
 lazyeval      0.2.2   2019-03-15 [1] CRAN (R 3.6.0)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
 lubridate     1.7.8   2020-04-06 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [3] CRAN (R 3.5.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
 modelr        0.1.6   2020-02-22 [1] CRAN (R 3.6.3)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.0)
 nlme          3.1-147 2020-04-13 [1] CRAN (R 3.6.3)
 pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.2)
 pkgbuild      1.0.7   2020-04-25 [1] CRAN (R 3.6.3)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
 plyr          1.8.6   2020-03-03 [1] CRAN (R 3.6.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.3)
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.3)
 purrr       * 0.3.4   2020-04-17 [1] CRAN (R 3.6.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
 Rcpp          1.0.4.6 2020-04-09 [1] CRAN (R 3.6.3)
 readr       * 1.3.1   2018-12-21 [1] CRAN (R 3.6.0)
 readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.0)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.3)
 reprex        0.3.0   2019-05-16 [1] CRAN (R 3.6.1)
 reshape       0.8.8   2018-10-23 [1] CRAN (R 3.6.1)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.2)
 rvcheck       0.1.8   2020-03-01 [1] CRAN (R 3.6.3)
 rvest         0.3.5   2019-11-08 [1] CRAN (R 3.6.1)
 scales      * 1.1.0   2019-11-18 [1] CRAN (R 3.6.1)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
 stringi       1.4.6   2020-02-17 [1] CRAN (R 3.6.3)
 stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
 taxize      * 0.9.95  2020-04-27 [1] CRAN (R 3.6.3)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
 tibble      * 3.0.1   2020-04-20 [1] CRAN (R 3.6.3)
 tidyr       * 1.0.2   2020-01-24 [1] CRAN (R 3.6.2)
 tidyselect    1.0.0   2020-01-27 [1] CRAN (R 3.6.2)
 tidytree      0.3.3   2020-04-02 [1] CRAN (R 3.6.3)
 tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 3.6.1)
 treeio      * 1.10.0  2019-10-29 [1] Bioconductor  
 triebeard     0.3.0   2016-08-04 [1] CRAN (R 3.6.1)
 urltools      1.7.3   2019-04-14 [1] CRAN (R 3.6.1)
 usethis       1.6.0   2020-04-09 [1] CRAN (R 3.6.3)
 vctrs         0.2.4   2020-03-10 [1] CRAN (R 3.6.3)
 withr         2.2.0   2020-04-20 [1] CRAN (R 3.6.3)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 3.6.3)
 zoo           1.8-7   2020-01-10 [1] CRAN (R 3.6.2)

[1] /home/agomez/R/x86_64-pc-linux-gnu-library/3.6
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```
</details>

Hello, first of all, thank you for an amazing package. I am experiencing an issue with the 'class2tree' function of taxize (v0.9.94 and v0.9.95). I am working with a list of species that are transformed with 'classification' and finally modified into a tree. However, sometimes, I found the error:

Error in if (currentIndex <= tmpEnv[[subList[i - 1]]]) { : 
  argument has lenght zero

During the classification there is no issue, all species are found in the NCBI database. I have tried to debug it but I do not have enough experience. With the same method, I am able to do the other 2 trees coming from the same dataset. I will appreciate if you can give me any clue about what could be the issue, moreover see if this is a bug. I am adding other information at the end.

Sorry for the inconvenience.
Best,
Adrián

The list I am using:
```r
$species
  [1] "Acartia bifilosa"               "Acartia hudsonica"              "Acartia tonsa"                  "Adenoides eludens"             
  [5] "Ahnfeltia plicata"              "Akashiwo sanguinea"             "Alexandrium margalefii"         "Alexandrium ostenfeldii"       
  [9] "Alexandrium pseudogonyaulax"    "Alexandrium tamarense"          "Algirosphaera robusta"          "Alitta succinea"               
 [13] "Alitta virens"                  "Alternaria alternata"           "Amphibalanus eburneus"          "Amphileptus litonotiformis"    
 [17] "Ancora sagittata"               "Ancoracysta twista"             "Ancyromonas sigmoides"          "Aphanomyces euteiches"         
 [21] "Aplanochytrium kerguelense"     "Arenicola marina"               "Aspergillus niger"              "Aspidisca aculeata"            
 [25] "Aspidisca leptaspis"            "Aspidisca magna"                "Asterionella glacialis"         "Attheya septentrionalis"       
 [29] "Aurelia aurita"                 "Aureococcus anophagefferens"    "Balanus glandula"               "Barnea candida"                
 [33] "Berkeleya rutilans"             "Betula pendula"                 "Blastocystis hominis"           "Bonnemaisonia hamifera"        
 [37] "Braarudosphaera bigelowii"      "Caecitellus paraparvulus"       "Cafeteria roenbergensis"        "Callithamnion collabens"       
 [41] "Carassius auratus"              "Cedrus deodara"                 "Centropages hamatus"            "Ceramium rubrum"               
 [45] "Cerastoderma edule"             "Cerataulina pelagica"           "Chaetoceros calcitrans"         "Chaetoceros contortus"         
 [49] "Chaetoceros curvisetus"         "Chaetoceros danicus"            "Chaetoceros decipiens"          "Chaetoceros didymus"           
 [53] "Chaetoceros diversus"           "Chaetoceros peruvianus"         "Chaetoceros seiracanthus"       "Chaetoceros throndsenii"       
 [57] "Childia groenlandica"           "Chloroidium saccharophilum"     "Chorda filum"                   "Ciliophrys infusionum"         
 [61] "Ciona intestinalis"             "Cladophora glomerata"           "Clavispora lusitaniae"          "Clupea harengus"               
 [65] "Clytia hemisphaerica"           "Cocconeis stauroneiformis"      "Conopeum seurati"               "Coscinodiscus granii"          
 [69] "Coscinodiscus radiatus"         "Craspedostauros amphoroides"    "Cryptomonas paramecium"         "Cyanea capillata"              
 [73] "Cyanophora paradoxa"            "Cyberlindnera fabianii"         "Cyclotella meneghiniana"        "Cylindrotheca closterium"      
 [77] "Cymbomonas tetramitiformis"     "Dexiostoma campyla"             "Dinophysis acuminata"           "Ditylum brightwellii"          
 [81] "Durinskia baltica"              "Ectocarpus siliculosus"         "Ectopsocus meridionalis"        "Electra crustulenta"           
 [85] "Emiliania huxleyi"              "Enibas tolerabilis"             "Epicarchesium corlissi"         "Epistylis elongata"            
 [89] "Euplotes vannus"                "Eurytemora affinis"             "Fucus gardneri"                 "Gadus morhua"                  
 [93] "Glaucocystis nostochinearum"    "Grammatophora oceanica"         "Guinardia delicatula"           "Gymnodinium catenatum"         
 [97] "Gyrodinium jinhaense"           "Hanseniaspora uvarum"           "Harveyella mirabilis"           "Hemiaulus sinensis"            
[101] "Hemiselmis cryptochromatica"    "Hemiselmis rufescens"           "Heterocapsa rotundata"          "Heterocapsa triquetra"         
[105] "Heteromastus filiformis"        "Heterosigma akashiwo"           "Hildenbrandia rubra"            "Holosticha diademata"          
[109] "Islandinium minutum"            "Karlodinium veneficum"          "Katablepharis japonica"         "Katablepharis remigera"        
[113] "Kryptoperidinium foliaceum"     "Labrus bergylta"                "Lemnicola hungarica"            "Lentomonas corrugata"          
[117] "Lepidodinium chlorophorum"      "Leptocylindrus danicus"         "Leptocylindrus minimus"         "Leptosphaeria biglobosa"       
[121] "Licmophora abbreviata"          "Licmophora grandis"             "Limecola balthica"              "Lingulodinium polyedra"        
[125] "Littorina littorea"             "Malassezia restricta"           "Massisteria marina"             "Melosira dubia"                
[129] "Merluccius merluccius"          "Mesanophrys carcini"            "Metschnikowia bicuspidata"      "Miamiensis avidus"             
[133] "Micromonas pusilla"             "Ministeria vibrans"             "Mya arenaria"                   "Mytilus trossulus"             
[137] "Nannochloropsis oceanica"       "Navicula perminuta"             "Nephroselmis pyriformis"        "Nitzschia longissima"          
[141] "Noctiluca scintillans"          "Obelia longissima"              "Opercularella lacerata"         "Oxnerella micra"               
[145] "Oxyrrhis marina"                "Paraflabellula hoguae"          "Parambassis ranga"              "Paramecium caudatum"           
[149] "Paramecynostomum diversicolor"  "Paramoeba pemaquidensis"        "Paramoeba perurans"             "Paranais litoralis"            
[153] "Peringia ulvae"                 "Peritromus faurei"              "Phaeocystis globosa"            "Phaeodactylum tricornutum"     
[157] "Placus salinus"                 "Planomonas micra"               "Podosira stelligera"            "Polydora cornuta"              
[161] "Polykrikos kofoidii"            "Porphyra purpurea"              "Porpostoma notata"              "Promesostoma caligulatum"      
[165] "Promesostoma cochleare"         "Protoceratium reticulatum"      "Protodinium simplex"            "Protoperidinium conicum"       
[169] "Protoperidinium pellucidum"     "Protoperidinium punctulatum"    "Protoperidinium thulesense"     "Provortex balticus"            
[173] "Prymnesium polylepis"           "Pseudo-nitzschia americana"     "Pseudo-nitzschia pungens"       "Pseudochattonella farcimen"    
[177] "Pseudochattonella verruculosa"  "Pseudopleurochloris antarctica" "Pseudosolenia calcar-avis"      "Pseudovorticella paracratera"  
[181] "Pterosperma cristatum"          "Pylaiella littoralis"           "Pyramimonas disomata"           "Pyramimonas olivacea"          
[185] "Pyropia haitanensis"            "Reckertia gemma"                "Rhizosolenia setigera"          "Rhodomela confervoides"        
[189] "Rhodomonas salina"              "Saccharina japonica"            "Saccharomycopsis fibuligera"    "Salmo trutta"                  
[193] "Salpingoeca urceolata"          "Saprolegnia parasitica"         "Scalibregma inflatum"           "Schizophyllum commune"         
[197] "Scruparia chelata"              "Skeletonema costatum"           "Sphaeroforma tapetis"           "Spirostrombidium agathae"      
[201] "Strombidinopsis batos"          "Synedra hyperborea"             "Teleaulax acuta"                "Teleaulax amphioxeia"          
[205] "Tenuicylindrus belgicus"        "Thalassiosira oceanica"         "Thraustochytrium aureum"        "Thraustochytrium kinnei"       
[209] "Trigonostomum penicillatum"     "Tripos fusus"                   "Tryblionella apiculata"         "Ulva intestinalis"             
[213] "Ulva prolifera"                 "Ulvella leptochaete"            "Uronema marinum"                "Verrucomonas bifida"           
[217] "Wickerhamiella sorbophila"      "Zostera marina"                

attr(,"groups")
# A tibble: 218 x 2
   species                     .rows    
   <chr>                       <list>   
 1 Acartia bifilosa            <int [1]>
 2 Acartia hudsonica           <int [1]>
 3 Acartia tonsa               <int [1]>
 4 Adenoides eludens           <int [1]>
 5 Ahnfeltia plicata           <int [1]>
 6 Akashiwo sanguinea          <int [1]>
 7 Alexandrium margalefii      <int [1]>
 8 Alexandrium ostenfeldii     <int [1]>
 9 Alexandrium pseudogonyaulax <int [1]>
10 Alexandrium tamarense       <int [1]>
# … with 208 more rows
```

Steps:

```r
nwk_sp_both <- df_sp %>% filter(file == 'Both') %>% select(species) %>% as.list()
sp_tree_both <- classification(nwk_sp_both$species, db = "ncbi")
tree_nwk_both <- class2tree(sp_tree_both, check = T)
write.tree(tree_nwk_both$phylo,file=paste(name, "_sp_tree.nwk", sep = ""))
```

### PR DESCRIPTION
**Pull request by trvinh**
## Description

A bug in the rank_indexing Fn within the class2tree caused wrongly updated indexes for some taxonomy ranks. By that, these ranks cannot be found in the indexing of the next species.

## Related Issue

Fix #818

### CODE REVIEW

**Comment by trvinh** [comment]
Again, I don't understand the error in travis-ci. Just FYI, the tests for `class2tree` passed on my computer.

File: tests/testthat/test-class2tree.R [hunk 1]
```diff
@@ -11,6 +11,32 @@ spnames <- c("Klattia flava", "Trollius sibiricus", "Arachis paraguariensis",
 dupnames <- c("Mus musculus", "Escherichia coli",
               "Haloferax denitrificans", "Mus musculus")
 
+test_that("internal functions of class2tree", {
+  skip_on_cran() # uses secrets
+  vcr::use_cassette("class2tree_classification_call", {
+    out <- classification(spnames, db = "ncbi", messages = FALSE)
+  })
+  
+  rankList <- taxize:::dt2df(lapply(out, taxize:::get_rank), idcol = FALSE)
```
Comment (sckott) [inline tests/testthat/test-class2tree.R:20]: you don't need to use `:::` for internal fxn calls, just call the fxn itself, so `get_rank` instead of `taxize:::get_rank`

File: tests/fixtures/class2tree_classification_dup_call.yml [hunk 2]
```diff
@@ -1,36 +1,36 @@
 http_interactions:
 - request:
     method: get
-    uri: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=taxonomy&term=Mus%2Bmusculus&api_key=<<entrez_api_token>>
```
Comment (sckott) [inline tests/fixtures/class2tree_classification_dup_call.yml:4]: looks like you aren't using an entrez API key? Do you have one?  If you don't, just don't commit changes to these fixture files since I don't think they should be changing anyway

File: tests/testthat/test-class2tree.R (hunk 1 above)
Comment (trvinh) [reply tests/testthat/test-class2tree.R]: I have removed them. I don't know that within the test one don't have to use `:::` for not exported function.

File: tests/fixtures/class2tree_classification_dup_call.yml (hunk 2 above)
Comment (trvinh) [reply tests/fixtures/class2tree_classification_dup_call.yml]: No, I am not using the entrez API key. Just like last time, I had to remove them so that the test can be passed. So you mean, I just need to change it on my end and not submit the changes to GitHub? If so, I've reset them. Hope that's fine.

Comment (sckott) [reply tests/fixtures/class2tree_classification_dup_call.yml]: Yes, just don't commit changes to any fixtures
